Download setup-vpn script.

diff --git a/local-deploy b/local-deploy
--- a/local-deploy
+++ b/local-deploy
@@ -3,6 +3,10 @@
 REMOTE_DEPLOY_COMMAND=remote-deploy
 GIT_VERSION=HEAD
 
+TINC_CLUSTER_URL=https://raw.githubusercontent.com/nsg/tinc-cluster/master/setup-vpn
+TINC_LOCAL_FILE=/tmp/setup-vpn
+TINC_SHA1SUM=382f44ff9c68d76e8670fbfb0a4bf2c5a1ce5f9f
+
 show_help() {
 	echo -e "\e[1m`basename $0`\e[0m based on commit $GIT_VERSION"
 	echo -e "This is a simple deployment tool written in bash."
@@ -166,6 +170,19 @@ save_metadata() {
 	remote_command $host save-metadata $domain $app $key $value
 }
 
+wget_sha1sum() {
+	if [ ! -f $2 ]; then
+		echo "Download $1 to $2"
+		wget -qO $2 $1
+	fi
+	echo "$3  $2" | sha1sum -c - > /dev/null
+	if [ $? != 0 ]; then
+		echo "Checksum error! $2 is not $3";
+		echo "Try to remove $2 and try again."
+		exit 1
+	fi
+}
+
 # Select mode
 case $1 in
 	config)
@@ -262,6 +279,9 @@ if [ $__domain ]; then
 fi
 [ $__debug ] && echo "hosts: $hosts"
 [ $__debug ] && echo "domain: $domain"
+
+# Download and verify setup-vpn from GitHub
+wget_sha1sum $TINC_CLUSTER_URL $TINC_LOCAL_FILE $TINC_SHA1SUM
 
 # Show config
 if [ $__show_config ]; then
